# populate_frontend.py
import os

FILES = {
    "frontend/package.json": '{\n  "name": "nmls-radar-frontend",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start",\n    "lint": "next lint"\n  },\n  "dependencies": {\n    "react": "^18.2.0",\n    "react-dom": "^18.2.0",\n    "next": "14.2.3",\n    "lucide-react": "^0.379.0",\n    "recharts": "^2.12.7",\n    "clsx": "^2.1.1",\n    "tailwind-merge": "^2.3.0",\n    "@clerk/nextjs": "^5.0.12"\n  },\n  "devDependencies": {\n    "typescript": "^5.4.5",\n    "@types/node": "^20.12.12",\n    "@types/react": "^18.3.3",\n    "@types/react-dom": "^18.3.0",\n    "postcss": "^8.4.38",\n    "tailwindcss": "^3.4.3",\n    "eslint": "^8.57.1",\n    "eslint-config-next": "14.2.3"\n  }\n}',
    "frontend/tailwind.config.ts": 'import type { Config } from "tailwindcss";\n\nconst config: Config = {\n  content: [\n    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",\n    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",\n    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",\n  ],\n  darkMode: "class",\n  theme: {\n    extend: {\n      colors: {\n        primary: "#09090B",\n        secondary: "#1E1B4B",\n        tertiary: "#1D4ED8",\n        accent: "#A78BFA",\n        neutral: "#FFFFFF",\n        "neutral-muted": "#94A3B8",\n        "background-card": "#0F172A",\n        "border-subtle": "#1F2937",\n      },\n      fontFamily: {\n        sans: ["Inter", "sans-serif"],\n        mono: ["JetBrains Mono", "monospace"],\n      },\n    },\n  },\n  plugins: [],\n};\nexport default config;',
    "frontend/src/styles/globals.css": '@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody {\n  background-color: #09090B;\n  color: #FFFFFF;\n  font-family: \'Inter\', sans-serif;\n}\n\n::-webkit-scrollbar {\n  width: 6px;\n  height: 6px;\n}\n::-webkit-scrollbar-track {\n  background: #09090B;\n}\n::-webkit-scrollbar-thumb {\n  background: #1F2937;\n  border-radius: 4px;\n}\n::-webkit-scrollbar-thumb:hover {\n  background: #3B82F6;\n}',
    "frontend/src/lib/api.ts": 'export interface LoanOfficer {\n  id: string;\n  nmls_id: number;\n  first_name: string;\n  last_name: string;\n  current_state: string;\n  license_status: string;\n  current_company_id?: string;\n  company?: {\n    id: string;\n    company_name: string;\n    company_nmls: number;\n    state: string;\n  };\n  first_seen_date: string;\n  created_at: string;\n}\n\nexport interface CompanyGrowth {\n  id: string;\n  company_name: string;\n  company_nmls: number;\n  state: string;\n  officer_count: number;\n}\n\nexport interface ChangeEvent {\n  id: string;\n  event_type: "NEW_LICENSE" | "COMPANY_TRANSFER" | "LICENSE_STATUS_CHANGE" | "NEW_STATE_APPROVAL";\n  nmls_id: number;\n  event_description: string;\n  old_value?: string;\n  new_value?: string;\n  detected_at: string;\n  processed_status: string;\n}\n\nconst BASE_URL = "http://127.0.0.1:8000/api/v1";\n\nexport async function fetchFromAPI(endpoint: string, options: RequestInit = {}) {\n  const url = `${BASE_URL}${endpoint}`;\n  try {\n    const res = await fetch(url, {\n      ...options,\n      headers: {\n        "Content-Type": "application/json",\n        "Authorization": "Bearer clerk_test_token_prototype",\n        ...options.headers,\n      },\n    });\n    if (!res.ok) {\n      throw new Error(`API error: ${res.status}`);\n    }\n    return await res.json();\n  } catch (err) {\n    console.error(`API execution failed: ${endpoint}:`, err);\n    throw err;\n  }\n}',
    "frontend/src/app/layout.tsx": 'import React from "react";\nimport type { Metadata } from "next";\nimport "../styles/globals.css";\n\nexport const metadata: Metadata = {\n  title: "NMLS Radar - AI Mortgage Intelligence",\n  description: "Automated mortgage licensing intelligence and sponsorship delta tracker.",\n};\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode;\n}) {\n  return (\n    <html lang="en">\n      <head>\n        <link rel="preconnect" href="https://fonts.googleapis.com" />\n        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />\n        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;700&display=swap" rel="stylesheet" />\n      </head>\n      <body className="antialiased">{children}</body>\n    </html>\n  );\n}'
}

def generate_website():
    print("Writing frontend web structures...")
    for path, content in FILES.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        print(f"Writing: {path}")
        with open(path, "w") as f:
            f.write(content)
    print("All frontend application source codes are synced locally!")

if __name__ == "__main__":
    generate_website()