FROM python:3.11-slim as builder

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.11-slim as runner

WORKDIR /home/backend

COPY --from=builder /root/.local /root/.local
COPY . /home/backend

ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/home/backend

EXPOSE 8000